name: Hanamboatra APK Tantsaha

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maka ny kaody
        uses: actions/checkout@v4

      - name: Mametraka Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Hanamboatra sy hanome alalana ny Gradle wrapper
        run: |
          chmod +x Gradle/wrapper/gradle-wrapper.properties
          if [ ! -f gradlew ]; then
            gradle wrapper --gradle-version 8.4
          fi
          chmod +x gradlew

      - name: Manamboatra APK
        run: ./gradlew assembleDebug

      - name: Mampakatra APK
        uses: actions/upload-artifact@v4
        with:
          name: Tantsaha-Matihanina-APK
          path: "**/build/outputs/apk/debug/*.apk"
