name: Générer APK Flutter

on:
  push:
    branches: [ "principal" ]
  pull_request:
    branches: [ "principal" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code du projet
        uses: actions/checkout@v4

      - name: Configurer Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configurer Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Récupérer les dépendances
        run: flutter pub get

      - name: Compiler l'APK
        run: flutter build apk --release

      - name: Sauvegarder l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Application-Flutter-APK
          path: build/app/outputs/flutter-apk/app-release.apk
